Repository thesoupgirl/408Proj, pull requests merged in 2018-02, with the labels that each got.

#14 UserStories 7,8,9 (day, week, month view)
  .DS_Store
  .gitignore
  EpsteinAndroid/.gitignore
  EpsteinAndroid/app/.gitignore
  EpsteinAndroid/app/build.gradle
  EpsteinAndroid/app/proguard-rules.pro
  EpsteinAndroid/app/src/androidTest/java/xyz/jhughes/epsteinandroid/ExampleInstrumentedTest.java
  EpsteinAndroid/app/src/main/AndroidManifest.xml
  EpsteinAndroid/app/src/main/ic_launcher-web.png
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/LoginActivity.java
  EpsteinAndroid/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  EpsteinAndroid/app/src/main/res/drawable/ic_launcher_background.xml
  EpsteinAndroid/app/src/main/res/layout/activity_login.xml
  EpsteinAndroid/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  EpsteinAndroid/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  EpsteinAndroid/app/src/main/res/mipmap-hdpi/ic_launcher.png
  EpsteinAndroid/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-mdpi/ic_launcher.png
  EpsteinAndroid/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  EpsteinAndroid/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  EpsteinAndroid/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  EpsteinAndroid/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/values/colors.xml
  EpsteinAndroid/app/src/main/res/values/strings.xml
  EpsteinAndroid/app/src/main/res/values/styles.xml
  EpsteinAndroid/app/src/test/java/xyz/jhughes/epsteinandroid/ExampleUnitTest.java
  EpsteinAndroid/build.gradle
  EpsteinAndroid/gradle.properties
  EpsteinAndroid/gradle/wrapper/gradle-wrapper.properties
  EpsteinAndroid/gradlew
  EpsteinAndroid/gradlew.bat
  EpsteinAndroid/settings.gradle
  client/components/UserPage.jsx
  package-lock.json
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/stressmanager/BackendApplication.java
  src/main/java/com/stressmanager/DBSetup.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
  src/test/java/com/stressmanager/RegressionTests.java
Labels: frontend

#15 hotfix -- yml
  .gitignore
  src/main/resources/application.yml
Labels: bug

#17 Android Sign In - Task #1
  .directory
  .gitignore
  EpsteinAndroid/app/build.gradle
  EpsteinAndroid/app/src/main/AndroidManifest.xml
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/LoginActivity.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/activities/CalendarActivity.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/activities/LoginActivity.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Advice.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Calendars/Calendar.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Calendars/Calendars.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Events/CalendarUser.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Events/Event.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Events/Events.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Events/Time.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/models/Me.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/networking/EpsteinApi.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/networking/EpsteinApiHelper.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/networking/LoggingInterceptor.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/networking/ReceivedCookiesInterceptor.java
  EpsteinAndroid/app/src/main/java/xyz/jhughes/epsteinandroid/utilities/SharedPrefsHelper.java
  EpsteinAndroid/app/src/main/res/drawable/ic_launcher.png
  EpsteinAndroid/app/src/main/res/layout/activity_calendar.xml
  EpsteinAndroid/app/src/main/res/layout/activity_login.xml
  EpsteinAndroid/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  EpsteinAndroid/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  EpsteinAndroid/app/src/main/res/values/strings.xml
  pom.xml
  src/main/java/com/stressmanager/BackendApplication.java
  src/main/java/com/stressmanager/OAuth2Helper.java
  src/main/java/com/stressmanager/Oauth2Params.java
  src/main/resources/application.properties
  src/main/resources/applicationy.yml
  src/main/resources/untitled
Labels: android, backend
